POST http://localhost:8081/doctor
Content-Type: application/json

{

    "name": "henrique",
    "lastname": "gomes",
    "medicalSpecialty": {
      "name": "les",
      "description": "lupus"
    },
    "description": "medico gastro hc",
    "phoneNumber": "81865845385"
}

###

GET http://localhost:8080/notes
Content-Type: application/json


###
GET http://localhost:8080/notes/662cf55982682b0101adf3cc
Content-Type: application/json



###
DELETE http://localhost:8080/notes/662cf55982682b0101adf3cc
Content-Type: application/json