POST http://localhost:8081/specialty
Content-Type: application/json

{

  "name": "lupus",
  "description": "lupus"

}

###

GET http://localhost:8080/notes
Content-Type: application/json


###
GET http://localhost:8080/notes/662cf55982682b0101adf3cc
Content-Type: application/json



###
DELETE http://localhost:8080/notes/662cf55982682b0101adf3cc
Content-Type: application/json